### ISSUE TITLE
Glitch on Safari iOS

### ISSUE THREAD

**Issue by olecrivain** [arcturus3/react-circular-gauge#2]
Hey,

Noticed a glitch on Safari iOS. The counters are hanging out in the top-left corner instead of being centered in the middle of the gauge.

![image](https://github.com/arcturus3/react-circular-gauge/assets/589788/3c27c43e-73dd-4407-bdd2-53f2a48a1108)

Fixing this would be awesome for iphone users.
Let me know if you need more info!

**Comment by arcturus3** [comment]
Thanks for reporting this! Should be fixed with version 1.1.1. Are you able to confirm for both iOS Safari and macOS Safari? (I borrowed an iPhone to test and I don't have a Mac.)

**Comment by olecrivain** [comment]
Thanks!
It works perfectly now

![image](https://github.com/arcturus3/react-circular-gauge/assets/589788/b8846c35-d8ec-46f3-ac33-5544a388cc11)
